spring:
  thymeleaf:
    cache: true
#  datasource:
#    url: jdbc:postgresql://host.docker.internal:5432/la-doc-uploader
management:
  endpoints:
    enabled-by-default: false
form-flow:
  disabled-flows:
    - flow: laDocUploader
      staticRedirectPage: /
  uploads:
    max-file-size: '5'
    default-doc-type-label: "NotSet"
