spring:
  flyway:
    placeholders:
      user_file_doc_type_default: "NotSet"
  thymeleaf:
    cache: true
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/la-doc-uploader
management:
  endpoints:
    enabled-by-default: false
form-flow:
  disabled-flows: ~
  uploads:
    max-file-size: '5'