form-flow:
  disabled-flows:
    - flow: laDigitalAssister
      staticRedirectPage: /
  pdf:
    path: ~
  inputs: 'org.ladocuploader.app.inputs.'
  path: 'flows-config.yaml'
  uploads:
    accepted-file-types: 'image/*,.jpeg,.jpg,.png,.pdf,.bmp,.gif,.doc,.docx,.odt,.ods,.odp'
    thumbnail-width: '64'
    thumbnail-height: '60'
    # 20 files maximum
    max-files: '20'
    # file size limit in MB
    # If this is not set then the server values below for servlet max-file-size and tomcat max POST size will not be set
    # which will cause the server to use the default values of 1MB preventing uploads larger than that.
    max-file-size: '5'
  mixpanel:
    api-key: ${MIXPANEL_API_KEY}
  aws:
    region: 'us-east-1'
    s3_bucket_name: ${AWS_BUCKET}
    access_key: ${AWS_ACCESS_KEY}
    secret_key: ${AWS_SECRET_KEY}
    cmk: ${AWS_CMK}
  address:
    disabled: true
    smarty:
      smarty_auth_id: ${SMARTY_AUTH_ID}
      smarty_auth_token: ${SMARTY_AUTH_TOKEN}
      smarty_url: "https://us-street.api.smartystreets.com/street-address"
spring:
  profiles:
    group:
      test:
        - test
        - form-flow-library-test
      dev:
        - dev
        - form-flow-library
      demo:
        - demo
        - form-flow-library
  security:
    user:
      name: ${DEFAULT_USER}
      password: ${DEFAULT_PASSWORD}
      roles: USER
  thymeleaf:
    cache: false
    template-resolver-order: 0
    check-template-location: true
  # TODO: move caching 0 to a dev only context?
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
        cachecontrol:
          max-age: 7d
    locale: ${DEFAULT_LOCALE}
    locale-resolver: fixed
  datasource:
    url: jdbc:postgresql://localhost:5432/la-doc-uploader
    username: la-doc-uploader
  servlet:
    multipart:
      max-file-size: ${form-flow.uploads.max-file-size}MB
      max-request-size: ${form-flow.uploads.max-file-size}MB
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            security:
              servlet:
                UserDetailsServiceAutoConfiguration: OFF
server:
  tomcat:
    max-http-form-post-size: ${form-flow.uploads.max-file-size}MB
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  servlet:
    session:
      persistent: true
sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 0.6
management:
  endpoints:
    enabled-by-default: false
