package org.ladocuploader.app.utils;

public enum Parish {
  ACADIA("Acadia"),
  ALLEN("Allen"),
  ASCENSION("Ascension"),
  ASSUMPTION("Assumption"),
  AVOYELLES("Avoyelles"),
  BEAUREGARD("Beauregard"),
  BIENVILLE("Bienville"),
  BOSSIER("Bossier"),
  CADDO("Caddo"),
  CALCASIEU("Calcasieu"),
  CALDWELL("Caldwell"),
  CAMERON("Cameron"),
  CATAHOULA("Catahoula"),
  CLAIBORNE("Claiborne"),
  CONCORDIA("Concordia"),
  DESOTO("DeSoto"),
  EAST_BATON_ROUGE("East Baton Rouge"),
  EAST_CARROLL("East Carroll"),
  EAST_FELICIANA("East Feliciana"),
  EVANGELINE("Evangeline"),
  FRANKLIN("Franklin"),
  GRANT("Grant"),
  IBERIA("Iberia"),
  IBERVILLE("Iberville"),
  JACKSON("Jackson"),
  JEFFERSON("Jefferson"),
  JEFFERSON_DAVIS("Jefferson Davis"),
  LAFAYETTE("Lafayette"),
  LAFOURCHE("Lafourche"),
  LASALLE("LaSalle"),
  LINCOLN("Lincoln"),
  LIVINGSTON("Livingston"),
  MADISON("Madison"),
  MOREHOUSE("Morehouse"),
  NATCHITOCHES("Natchitoches"),
  ORLEANS("Orleans"),
  OUACHITA("Ouachita"),
  PLAQUEMINES("Plaquemines"),
  POINTE_COUPEE("Pointe Coupee"),
  RAPIDES("Rapides"),
  RED_RIVER("Red River"),
  RICHLAND("Richland"),
  SABINE("Sabine"),
  ST_BERNARD("St. Bernard"),
  ST_CHARLES("St. Charles"),
  ST_HELENA("St. Helena"),
  ST_JAMES("St. James"),
  ST_JOHN("St. John"),
  ST_LANDRY("St. Landry"),
  ST_MARTIN("St. Martin"),
  ST_MARY("St. Mary"),
  ST_TAMMANY("St. Tammany"),
  TANGIPAHOA("Tangipahoa"),
  TENSAS("Tensas"),
  TERREBONNE("Terrebonne"),
  UNION("Union"),
  VERMILION("Vermilion"),
  VERNON("Vernon"),
  WASHINGTON("Washington"),
  WEBSTER("Webster"),
  WEST_BATON_ROUGE("West Baton Rouge"),
  WEST_CARROLL("West Carroll"),
  WEST_FELICIANA("West Feliciana"),
  WINN("Winn");
  private final String displayName;

  Parish(String displayName) {
    this.displayName = displayName;
  }

  public String getDisplayName() {
    return displayName;
  }
}
